export const COMMON_REGISTER_APP = 'COMMON_REGISTER_APP';
export const COMMON_REGISTER_APP_SUCCESS = 'COMMON_REGISTER_APP_SUCCESS';
export const COMMON_REGISTER_APP_FAIL = 'COMMON_REGISTER_APP_FAIL';
